version: "3"
services:
  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./backend
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=contact_db
    depends_on:
      - mysql
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - PORT=3000

volumes:
  mysql-data:

